POST http://127.0.0.1:8090/authentication/signup
Content-Type: application/json

{
  "name": "Ahmed",
  "dob": "2006-01-02T15:04:05Z",
  "email": "ahmed244444@example.com",
  "password": "Password123"
}